services:
  api_app:
    image: "rust"
    working_dir: "/app"
    volumes:
      - "./:/app/:ro"
      - "/app/target/"
    env_file: "docker.env"
    command: ["cargo", "run", "--release"]

  nginx_proxy:
    image: "nginx:alpine"
    ports:
      - "127.0.0.1:8089:80"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
