name: "Test Suite"
on:
  push:
    branches:
      - "main"

jobs:
  test:
    name: cargo test
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - run: |
          source example-environs.bash
          cargo check
          cargo fmt --all -- --check
          cargo test --test integration_test
